### ISSUE TITLE
code for visualize

### ISSUE THREAD

**Issue by yrk-creator** [dvlab-research/Stratified-Transformer#7]
Excuse me , may I ask you whether have the code for visualizatioin。 And the training time is so long , i want to ask which cost the most of the time, is the model training or data load cost too much time

**Comment by X-Lai** [comment]
Which visualization do you want? 

As for the training time, it is because the operation of window attention is time-consuming. But in fact, I recommend training for only 50 epochs, since the performance gap with training for 100 epochs is merely 1.0% miou, and meanwhile training for 50 epochs does not consume too much time.

**Comment by yrk-creator** [comment]
thank you very much, I will try it. Could you share the visualization code for the semantic prediction result

**Comment by X-Lai** [comment]
You can use the following function to output the .obj file, and open it with MeshLab.
```
def write_obj(points, colors, out_filename):
    N = points.shape[0]
    fout = open(out_filename, 'w')
    for i in range(N):
        c = colors[i]
        fout.write('v %f %f %f %d %d %d\n' % (points[i, 0], points[i, 1], points[i, 2], c[0], c[1], c[2]))
    fout.close()
```
